using System;

namespace ProjectEuler.Problem2
{
    public static class Problem2
    {
        //    Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
        //
        //    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
        //
        //    By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
        public static void Solve()
        {
            const int target = 4_000_000;
            const int targetTemp = 100;

            var x = 2;
            var y = 1;
            var result = 0;

            while (x < target)
            {
                if (x % 2 == 0)
                {
                    result += x;
                }
                var temp = x;
                x = y + x;
                y = temp;
            }
            Console.WriteLine($"The answer is {result}.");
        }
    }
}